export type DimensionType = "original" | "entropy" | "quantum" | "void" | "bio" | "mech";

export interface DimensionEntry {
  id: string;
  name: string;
  description: string;
  type: DimensionType;
  color: string;
  threatLevel: "low" | "medium" | "high" | "extreme" | "unknown";
  discoveredAt: string;
  keyEvents: string[];
  inhabitants: string[];
  energySignature: string;
}

export interface ChronicleEntry {
  id: string;
  date: string;
  title: string;
  description: string;
  category: "event" | "discovery" | "battle" | "character" | "technology";
  dimensionId: string;
  relatedHeroIds: string[];
  quote?: string;
  quoteAuthor?: string;
}

export const DIMENSIONS: DimensionEntry[] = [
  {
    id: "original",
    name: "原点维度",
    description: "人类文明的发源地，也是维度裂痕首次出现的地方。在锚点装置的保护下，是抵御维度入侵的最后防线。",
    type: "original",
    color: "var(--primary)",
    threatLevel: "high",
    discoveredAt: "2147年3月15日",
    keyEvents: ["维度裂痕首次出现", "锚点装置激活", "幸存者基地建立", "第一场防御战胜利"],
    inhabitants: ["人类幸存者", "维度入侵者"],
    energySignature: "蓝色量子共振",
  },
  {
    id: "entropy",
    name: "熵增维度",
    description: "一切都在加速衰败的维度。熵能在这里以可见的速度侵蚀一切——建筑、生命、甚至时间本身。维度核心由「熵之主」守护。",
    type: "entropy",
    color: "var(--entropy)",
    threatLevel: "extreme",
    discoveredAt: "2147年4月3日",
    keyEvents: ["首次熵能污染检测", "熵增抑制器发现", "古代实验室探索", "熵之主觉醒"],
    inhabitants: ["熵能实体", "分裂者", "腐蚀者", "熵之主"],
    energySignature: "绿色熵能辐射",
  },
  {
    id: "quantum",
    name: "量子维度",
    description: "量子纠缠现象的核心维度。多个维度在这里同时存在，时间是非线性的。先驱者文明的遗迹遍布整个维度，它们的AI「幻影」仍在守护着这个维度。",
    type: "quantum",
    color: "var(--quantum)",
    threatLevel: "extreme",
    discoveredAt: "2147年5月21日",
    keyEvents: ["量子信号接收", "先驱者遗迹发现", "量子之主击败", "先驱者真相揭示"],
    inhabitants: ["先驱者AI", "量子实体", "幻影", "巨兽"],
    energySignature: "青色量子纠缠",
  },
  {
    id: "void",
    name: "虚空深渊",
    description: "所有维度的尽头。在这里，一切能量都会被吞噬，光线、声音、甚至意识都会逐渐消失。虚空深渊的底部存在着「吞噬者」——被认为是维度裂痕的最终源头。",
    type: "void",
    color: "var(--void)",
    threatLevel: "unknown",
    discoveredAt: "2147年7月8日",
    keyEvents: ["虚空信号首次探测", "虚空边界探索", "吞噬者发现"],
    inhabitants: ["虚空实体", "吞噬者", "迷失的灵魂"],
    energySignature: "暗紫色虚空能量",
  },
  {
    id: "bio",
    name: "生物维度",
    description: "由纯粹的生命能量构成的维度。这里的生物不需要食物和水，它们直接从维度能量中获取养分。蝰蛇的毒素来源就是这个维度——但她的身世仍是一个谜。",
    type: "bio",
    color: "var(--success)",
    threatLevel: "medium",
    discoveredAt: "2147年6月14日",
    keyEvents: ["生物维度入口发现", "蝰蛇起源线索", "生命能量提取技术"],
    inhabitants: ["生物能量体", "巨型植物", "毒素生命"],
    energySignature: "绿色生命能量",
  },
];

export const CHRONICLES: ChronicleEntry[] = [
  {
    id: "chr-001",
    date: "2147年3月15日",
    title: "维度裂痕首次出现",
    description: "全球多个地点同时出现维度裂痕。来自未知维度的生物涌入地球，人类文明在三天内崩溃。这是人类历史上最黑暗的一天。",
    category: "event",
    dimensionId: "original",
    relatedHeroIds: [],
    quote: "天空裂开了。从那道裂缝中涌出的，不是光，而是噩梦。",
    quoteAuthor: "幸存者日记",
  },
  {
    id: "chr-002",
    date: "2147年3月18日",
    title: "锚点装置激活",
    description: "在科学家们的努力下，最后一个锚点装置被激活。这个装置能够稳定周围的维度能量，阻止裂痕继续扩大。幸存者开始在锚点周围建立基地。",
    category: "technology",
    dimensionId: "original",
    relatedHeroIds: ["recon"],
    quote: "我们找到了一个支点。现在，我们需要撬动整个地球。",
    quoteAuthor: "林锐",
  },
  {
    id: "chr-003",
    date: "2147年3月22日",
    title: "南极科考站救援",
    description: "一支救援队被派往南极「冰穹-A」科考站。他们在那里发现了独自存活了17天的陈寒（液氮），他已经利用自制武器击杀了超过30只维度生物。",
    category: "battle",
    dimensionId: "original",
    relatedHeroIds: ["nitrogen", "twilight"],
    quote: "寒冷不是敌人，是武器。",
    quoteAuthor: "陈寒",
  },
  {
    id: "chr-004",
    date: "2147年3月28日",
    title: "第一场防御战胜利",
    description: "锚点基地成功抵御了第一次大规模维度入侵。石坚（堡垒）在战斗中驾驶推土机撞向敌人，被大家称为「第一道防线」。",
    category: "battle",
    dimensionId: "original",
    relatedHeroIds: ["bastion"],
    quote: "我的身后是基地，我不退。",
    quoteAuthor: "石坚",
  },
  {
    id: "chr-005",
    date: "2147年4月1日",
    title: "红区医疗站建立",
    description: "白暮（暮蝶）在锚点基地附近建立了前线医疗站。她发现维度能量对生物组织有奇特的修复效应，开始研究「维度共振修复」技术。",
    category: "technology",
    dimensionId: "original",
    relatedHeroIds: ["twilight"],
    quote: "只要还有一口气，我就不会让任何人倒下。",
    quoteAuthor: "白暮",
  },
  {
    id: "chr-006",
    date: "2147年4月3日",
    title: "熵增维度发现",
    description: "锚点传感器检测到一种全新的维度信号——熵能。这种能量正在加速侵蚀锚点周围的区域。熵增维度的入口被定位。",
    category: "discovery",
    dimensionId: "entropy",
    relatedHeroIds: [],
    quote: "衰败不是终点，而是另一种形式的增长。",
    quoteAuthor: "维度研究日志",
  },
  {
    id: "chr-007",
    date: "2147年4月5日",
    title: "裂痕核心侦查任务",
    description: "雷豹（豹）率领一支12人小队深入裂痕核心进行侦查。全队只有他一人活着回来，但带回了关于维度生物行为模式的关键情报。",
    category: "battle",
    dimensionId: "original",
    relatedHeroIds: ["leopard"],
    quote: "敌人不会因为你的恐惧而手下留情，所以——露出獠牙吧。",
    quoteAuthor: "雷豹",
  },
  {
    id: "chr-008",
    date: "2147年4月12日",
    title: "体育场保卫战",
    description: "隼在世界射击锦标赛上，于混乱中拿起狙击步枪击杀37只维度生物，保护了整个体育馆的观众。她发现了维度生物的能量核心弱点。",
    category: "battle",
    dimensionId: "original",
    relatedHeroIds: ["falcon"],
    quote: "一枪，一个核心。不需要第二枪。",
    quoteAuthor: "隼",
  },
  {
    id: "chr-009",
    date: "2147年4月18日",
    title: "古代实验室探索",
    description: "在熵增维度中，探索队发现了一座前文明时代的实验室。全息屏幕上显示着「熵增抑制器」的蓝图——这是对抗熵能侵蚀的关键技术。",
    category: "discovery",
    dimensionId: "entropy",
    relatedHeroIds: [],
    quote: "我们不是第一个面对维度裂痕的文明。上一个文明没有成功——但我们不会。",
    quoteAuthor: "探索队报告",
  },
  {
    id: "chr-010",
    date: "2147年4月25日",
    title: "蝰蛇觉醒",
    description: "在生物维度附近的一个实验室废墟中，一个全身被绿色液体浸泡的女性苏醒。她失去了所有记忆，但体内拥有数十种致命的维度毒素。她为自己取名「万毒」。",
    category: "character",
    dimensionId: "bio",
    relatedHeroIds: ["viper"],
    quote: "毒不是武器，是我身体的一部分。",
    quoteAuthor: "万毒",
  },
  {
    id: "chr-011",
    date: "2147年5月5日",
    title: "熵增抑制器制造成功",
    description: "利用古代实验室的蓝图，锚点基地的工程师们成功制造了第一台熵增抑制器。这台设备能够暂时稳定熵能侵蚀，为基地争取了宝贵的时间。",
    category: "technology",
    dimensionId: "entropy",
    relatedHeroIds: [],
    quote: "我们不是创造者，我们是继承者。",
    quoteAuthor: "工程日志",
  },
  {
    id: "chr-012",
    date: "2147年5月21日",
    title: "量子维度发现",
    description: "熵增抑制器启动后，锚点传感器检测到了一种全新的维度信号——量子纠缠。七个不同的维度同时向原点维度发送信号，信号带有明确的人工编码模式。",
    category: "discovery",
    dimensionId: "quantum",
    relatedHeroIds: [],
    quote: "有人，或者有什么东西，在试图与你们建立联系。",
    quoteAuthor: "传感器分析报告",
  },
  {
    id: "chr-013",
    date: "2147年6月1日",
    title: "先驱者文明发现",
    description: "在量子维度中，探索队发现了先驱者文明的遗迹。这个高度发达的古代文明曾经试图创造无限的维度能量，但实验失控，撕裂了维度屏障。",
    category: "discovery",
    dimensionId: "quantum",
    relatedHeroIds: [],
    quote: "他们不是神，他们只是比我们更早犯错的凡人。",
    quoteAuthor: "侦察小队报告",
  },
  {
    id: "chr-014",
    date: "2147年6月14日",
    title: "生物维度入口发现",
    description: "在维度边界探索中，侦察小队发现了一个充满生命能量的维度入口。这个维度中的生物直接从维度能量中获取养分，不需要食物和水。",
    category: "discovery",
    dimensionId: "bio",
    relatedHeroIds: ["recon"],
    quote: "生命可以以我们无法想象的形式存在。",
    quoteAuthor: "林锐",
  },
  {
    id: "chr-015",
    date: "2147年6月28日",
    title: "量子之主击败",
    description: "在量子维度的核心，探索队面对了先驱者AI「幻影」。经过一场惊心动魄的战斗，幻影被击败，先驱者留下的抑制装置被激活。",
    category: "battle",
    dimensionId: "quantum",
    relatedHeroIds: [],
    quote: "我们不是来摧毁你的，我们只是来结束这一切。",
    quoteAuthor: "战斗记录",
  },
  {
    id: "chr-016",
    date: "2147年7月1日",
    title: "全英雄集结",
    description: "七位英雄在锚点基地正式集结。液氮、暮蝶、豹、侦察、蝰蛇、隼、堡垒——他们代表了人类对抗维度入侵的全部力量。",
    category: "event",
    dimensionId: "original",
    relatedHeroIds: ["nitrogen", "twilight", "leopard", "recon", "viper", "falcon", "bastion"],
    quote: "七个人，七个维度，一个目标。",
    quoteAuthor: "基地日志",
  },
  {
    id: "chr-017",
    date: "2147年7月8日",
    title: "虚空深渊边界探索",
    description: "维度传感器在维度边界检测到了一种未知的维度信号——虚空。这个维度的能量签名与所有已知维度都不同，它似乎在「吞噬」其他维度的能量。",
    category: "discovery",
    dimensionId: "void",
    relatedHeroIds: [],
    quote: "虚空不是空的。它装满了已死维度的残骸。",
    quoteAuthor: "维度研究报告",
  },
  {
    id: "chr-018",
    date: "2147年7月15日",
    title: "吞噬者确认",
    description: "经过多次探索，科学家确认虚空深渊的底部存在着一个被称为「吞噬者」的实体。它被认为是维度裂痕的最终源头——所有维度能量都在被它缓慢吞噬。",
    category: "discovery",
    dimensionId: "void",
    relatedHeroIds: [],
    quote: "维度裂痕不是因为能量太多，而是因为能量在消失。",
    quoteAuthor: "科学报告",
  },
  {
    id: "chr-019",
    date: "2147年7月20日",
    title: "BossRush试炼开启",
    description: "为了训练英雄们对抗越来越强大的维度首领，锚点基地建立了BossRush试炼系统。英雄们可以在模拟环境中挑战所有已知的维度首领。",
    category: "technology",
    dimensionId: "original",
    relatedHeroIds: [],
    quote: "在试炼中流汗，在战场上少流血。",
    quoteAuthor: "石坚",
  },
  {
    id: "chr-020",
    date: "2147年7月27日",
    title: "最终战役前夕",
    description: "英雄们已经穿越了所有已知维度，击败了所有维度守护者。但虚空深渊的吞噬者仍在等待——它正在缓慢地吞噬着所有维度。最终战役即将开始。",
    category: "event",
    dimensionId: "void",
    relatedHeroIds: ["nitrogen", "twilight", "leopard", "recon", "viper", "falcon", "bastion"],
    quote: "我们穿越了所有维度，面对了所有恐惧。现在，只剩下最后一个。",
    quoteAuthor: "未知",
  },
];